# Generated by Django 3.2.6 on 2021-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='address_display',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
